language: node_js
sudo: required
before_install:
  - npm install -g node-gyp
  - npm install --save bufferutil@3 ws@1
  - "npm install -g npm@latest"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
